# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
from pprint import pprint
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
file_to_load = "cities.csv"
data = pd.read_csv(file_to_load,low_memory=False)
pprint(data)
weather_data = data[["City","Lat","Lon","Humidity","Country"]]
weather_data

     Unnamed: 0             City    Lat     Lon  Max Temp  Humidity  \
0             0           noumea -22.28  166.46     64.40        82
1             1        jamestown  42.10  -79.24     63.00       100
2             2           barrow  71.29 -156.79     42.80        93
3             3           aitape  -3.14  142.35     78.60        83
4             4  sfantu gheorghe  45.87   25.78     84.00        42
..          ...              ...    ...     ...       ...       ...
568         568    pacific grove  12.48  -16.55     87.80        84
569         569             teya  32.19 -115.00     95.00        40
570         570           sokoto  13.64   16.49     94.91        39
571         571    makakilo city  52.11 -101.27     65.10        76
572         572           ithaca  55.28 -114.77     51.80       100

     Cloudiness  Wind Speed Country        Date
0            75        5.44      NC  1970-01-01
1            40        3.11      US  1970-01-01
2            90       14.99      US  1970-01-01
3             1        6.85      PG  1970-01-01
4           100        1.99      RO  1970-01-01
..          ...         ...     ...         ...
568          40        4.70      SN  1970-01-01
569           1        5.82      MX  1970-01-01
570         100        9.62      TD  1970-01-01
571          70        3.51      CA  1970-01-01
572           1        2.46      CA  1970-01-01

[573 rows x 10 columns]

                City    Lat     Lon  Humidity Country
0             noumea -22.28  166.46        82      NC
1          jamestown  42.10  -79.24       100      US
2             barrow  71.29 -156.79        93      US
3             aitape  -3.14  142.35        83      PG
4    sfantu gheorghe  45.87   25.78        42      RO
..               ...    ...     ...       ...     ...
568    pacific grove  12.48  -16.55        84      SN
569             teya  32.19 -115.00        40      MX
570           sokoto  13.64   16.49        39      TD
571    makakilo city  52.11 -101.27        76      CA
572           ithaca  55.28 -114.77       100      CA

[573 rows x 5 columns]

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

humidity = weather_data[["Humidity"]].astype(float)
lat_lon = weather_data[["Lat","Lon"]]
fig = gmaps.figure() 
fig.add_layer(gmaps.heatmap_layer(lat_lon, weights=(humidity["Humidity"]) ))

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
utopia = data[["City","Lat","Lon","Humidity","Wind Speed","Max Temp","Country"]]
utopia = utopia.loc[(utopia["Max Temp"] <= 80) & (utopia["Max Temp"] >= 75) & (utopia["Humidity"] <= 80) & (utopia["Wind Speed"] <=30)]
utopia

                City    Lat     Lon  Humidity  Wind Speed  Max Temp Country
45            touros  22.08 -159.32        74       12.75     78.80      US
48    ciudad bolivar  26.78 -101.42        57        1.01     78.01      MX
72            avarua -20.21   57.76        73       16.11     75.20      MU
73        bredasdorp -23.86   35.38        65       20.80     78.80      MZ
79      quatre cocos  33.08  -16.33        65       12.75     77.00      PT
97       grand-santi  39.84   69.53        34       11.18     78.80      KG
98        nikolskoye -21.36   55.77        64       17.22     77.00      RE
106             nuuk  -9.80 -139.03        78       21.12     78.40      PF
111           vicuna -20.34   57.76        73       16.11     75.20      MU
113         victoria -20.41   57.70        73       16.11     75.20      MU
114      east london  -4.20   36.93        26       10.96     79.65      TZ
126        mahebourg  32.67  -17.10        64        4.63     77.00      PT
136      barentsburg  45.67    4.08        41        3.36     78.80      FR
137             lebu -20.52   57.52        73       16.11     75.20      MU
147             hami  38.03 -121.88        73        4.07     77.00      US
161         westport  49.07   23.86        57        4.47     78.80      UA
162          urdzhar  -8.47  140.33        76       12.55     75.29      ID
163        taolanaro -16.48 -151.75        78       13.73     77.85      PF
174          talnakh -21.37   55.62        64       17.22     77.00      RE
197         zhigansk -17.71  -39.25        62        6.91     79.50      BR
204          itarema  17.89  -77.59        75        3.60     79.74      JM
205          gobabis  46.62   10.70        53        4.70     77.00      IT
222   cabo san lucas  38.42 -121.42        73        4.16     78.01      US
223          del rio -20.33  -40.29        74       10.29     79.00      BR
224        umzimvubu  54.95   31.09        50        6.71     75.20      RU
236            manta  32.30   -9.24        61       23.94     78.75      MA
265              mao  48.29    4.05        53        9.17     75.20      FR
272           kodiak  37.32   -8.80        61       12.91     78.85      PT
280    mount gambier -16.70 -151.02        78       13.40     78.10      PF
286     ponte de sor -20.01   57.66        66        8.99     75.00      MU
291         khambhat  -5.14  119.42        73        4.70     77.00      ID
294       srivardhan   5.61   -3.16        75        5.79     78.10      CI
343        grindavik  50.15   48.57        27       12.77     75.67      RU
357           nacala  49.58    0.33        68        8.05     78.01      FR
361          chicama  50.17    8.57        41       10.29     79.00      DE
368     inderborskiy -17.07   15.73        11        6.93     78.80      AO
387     san fernando  13.02   31.87        70        5.68     79.39      SD
402         saleaula -20.08  -49.91        47       15.03     79.74      BR
404          margate  43.28   -8.21        73       13.87     75.20      ES
416           broome  -8.84   13.23        73        4.70     75.20      AO
421            tokat   7.62  -71.49        75        2.13     78.62      VE
429      kattivakkam  -1.57    9.26        76       10.76     78.89      GA
430            amapa  -7.95  110.28        78       11.03     76.64      ID
431           awbari -18.95  -57.80        73       11.41     77.00      BO
448        sarangani   5.26   -0.76        79       12.86     77.67      GH
458          lunglei  34.58 -117.41        45        1.99     77.00      US
460        egvekinot  -1.95   18.27        65        2.42     78.60      CD
463  punta de piedra  38.93  100.45        17        9.42     79.34      CN
473    bambanglipuro  34.39   67.02        16       17.54     78.58      AF
489  haines junction  -9.29  -76.01        53        0.72     75.72      PE
525        naro moru  -0.91  122.88        76        7.09     75.27      ID
529           xining -17.74  -46.17        50       10.98     79.30      BR
530            qeshm -15.68  -38.95        71        6.73     78.55      BR
551          natchez  29.85   80.53        76        2.26     75.49      IN
563    batagay-alyta  42.25   -2.50        60        2.24     75.20      ES

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
city_coord_df = utopia[["Lat","Lon"]]
hotel_df = []
no_hotel_counter = 0

for i,cities in (city_coord_df.iterrows()):

    try:
        latlonkey = str(cities["Lat"]) + "," + str(cities["Lon"])
        gurl = f"https://maps.googleapis.com/maps/api/place/nearbysearch/json?keyword=Hotel&radius=5000&location={latlonkey}&key={g_key}"

        response = requests.get(gurl)    
        hotel_data = response.json()
        hotel_df.append(hotel_data["results"][0]["name"])
        
    except IndexError:
        hotel_df.append("No hotel near by.")
        no_hotel_counter += 1

In [6]:
#Add hotel names to new dataframe
utopia_hotels = utopia.copy()
utopia_hotels =utopia_hotels.reset_index()
hotel_df = pd.DataFrame(hotel_df)
utopia_hotels["Hotel Name"] = hotel_df.astype(str)

In [7]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in utopia_hotels.iterrows()]
locations = utopia_hotels[["Lat", "Lon"]]

In [8]:
# Add marker layer ontop of heat map
gmaps.configure(api_key=g_key)

fig = gmaps.figure()
heatmap_layer = gmaps.heatmap_layer(locations)
fig.add_layer(heatmap_layer)

markers = gmaps.marker_layer(locations,info_box_content =hotel_info)
fig.add_layer(markers)
fig

# Display figure

Figure(layout=FigureLayout(height='420px'))